version: '2'

run:
  timeout: 5m
  allow-parallel-runners: true
  relative-path-mode: cfg

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - lll
    - loggercheck
    - mirror
    - misspell
    - mnd
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
      - path: ^test/e2e/
        linters:
          - goconst
      # some nodes are carbon copies of each other but use differnt values and functions.
      # satisfying dupl for these would just lead to unreadable code
      # with structs that just carry numerous function references.
      # tripped by JSONField and YAMLField which are nearly identical in
      # flow _except_ for every function/method they use (aside from two
      # map operations).
      - path: ^nodes/std/
        linters:
          - dupl

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: disable
